# Copyright (c) 2024 by SPYDER.
#
# This software is proprietary information of SPYDER.
# Unauthorized use, copying, modification, distribution, and/or
# disclosure is strictly prohibited, except as provided under the terms
# of the commercial license agreement you have entered into with
# SPYDER.
#
# For more details, see the LICENSE file in the root directory of this
# source code repository or contact SPYDER at info@spyder.org.

exclude: '^$'
fail_fast: true 
repos:
  -   repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
      -   id: detect-secrets
          name: Detect secrets
          language: python
          entry: detect-secrets-hook
          args: [
            '--baseline', 
            '.secrets.baseline',
            '--exclude-files',
            '(_test\.go$|/testdata/)',
            ]
  -   repo: https://github.com/sqlfluff/sqlfluff 
      rev: 3.2.4
      hooks:
      -   id: sqlfluff-fix
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
      -   id: check-json
      -   id: check-merge-conflict
      -   id: check-yaml
