name: auto-merge-deps

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
